### ISSUE TITLE
Xcode 15.3 and App store connect issue

### ISSUE THREAD

**Issue by Falahmad** [googlemaps/google-maps-ios-utils#460] opened 2024-03-08 03:06 UTC
Xcode version

15.3

Google utils SDK version

4.2.2

Dependency Manager

SPM

SDK Framework

Core

Goals

Archive my application and upload it to the App Store.

Expected results

Processing of the application on the Appstore connect without issues.

Actual results
![IMG_0057](https://github.com/googlemaps/google-maps-ios-utils/assets/12194010/38d29086-a13d-49e1-bf16-35879922b506)

**Comment by wangela** [comment] 2024-03-08 03:07
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@Falahmad Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by wangela** [comment] 2024-03-08 19:46
Marking this duplicate of #459

**Closed by wangela** 2024-03-08 19:46 UTC
Labels: status: duplicate, type: bug
