### ISSUE TITLE
Minimum bucket size for clustering

### ISSUE THREAD

**Issue by trant** [googlemaps/google-maps-ios-utils#46] opened 2016-10-01 17:56 UTC
I would only like to cluster if the number of elements is > than a certain limit otherwise the current one (think is 4) is overkill for some use cases. Is this possible?

**Comment by mountainvat** [comment] 2016-10-03 22:39
Duplicate of https://github.com/googlemaps/google-maps-ios-utils/issues/18

**Closed by mountainvat** 2016-10-03 22:39 UTC
