### ISSUE TITLE
Change style (specific icon and title) on features from GeoJSON parser

### ISSUE THREAD

**Issue by juvs** [googlemaps/google-maps-ios-utils#135] opened 2017-08-31 02:40 UTC
Maybe is something is already answered, but how I can change the style of features from GeoJSON parser based on properties from any single feature?

I have the following:

```swift
    let path = Bundle.main.path(forResource: "GeoJSON_sample", ofType: "json")
    let url = URL(fileURLWithPath: path!)
    geoJsonParser = GMUGeoJSONParser(url: url)
    geoJsonParser.parse()
    
   // MARK: Here try to iterate features and change style, but there's no way no get properties from feature, 
   // Also, create a new GMUStyle and set iconUrl and title and nothing changes, 
   // I set iconUrl using asset key name filename from Assets 

    renderer = GMUGeometryRenderer(map: mapView, geometries: geoJsonParser.features)

    renderer.render()
```
Any help appreciated!

Regards

**Comment by SiddharthChopra** [comment] 2017-12-06 11:32
I am also facing the same issue with this as I want to changes style

**Comment by devcsantiago** [comment] 2017-12-08 02:12
You should be available to use this:

`let features = geoJsonParse.features as? [GMUFeature]
for features in features {
feature.properties // Return properties
}`

The only problem its that doesn't work :(

**Comment by sidlauskaslukas** [comment] 2018-04-16 11:54
I can confirm that it still doesn't work and "properties" is not available for use.

**Comment by return1225** [comment] 2018-07-11 08:32
Here is a sample to iterate rendering all features with customized style.
Try it :)
```swift
let strokeColor = UIColor(red: 1, green: 0, blue: 0, alpha: 1)
for feature in geoJsonParser.features {
    feature.style = GMUStyle(styleID: "12345", stroke: strokeColor, fill: UIColor.clear, width: 2.0, scale: 1.0, heading: 0.0, anchor: CGPoint(x: 0, y: 0), iconUrl: "url", title: "title", hasFill: false, hasStroke: true)
}
```

**Comment by minhmera** [comment] 2019-09-12 03:24
Hi guys,
 Is there any way to access properties ? i want to change style for each feature with some specific condition

**Comment by arriolac** [comment] 2020-01-15 21:00
@juvs you should be able to access the properties of a feature, it requires some type checking though since `geoJsonParser.features` is of type `[GMUGeometryContainer]` and not `[GMUFeature]`.

i.e.
```
for obj in geoJsonParser.features {
  if let feature = obj as? GMUFeature {
    let properties = feature.properties
    // Do something with properties here
  }
}
```

**Comment by arriolac** [comment] 2020-01-15 21:04
Closing. Please reopen if this does not resolve your issue.

**Closed by arriolac** 2020-01-15 21:04 UTC
Labels: priority: p2, type: question

**Comment by mallikarjuna0308** [comment] 2020-03-05 12:52
> @juvs you should be able to access the properties of a feature, it requires some type checking though since `geoJsonParser.features` is of type `[GMUGeometryContainer]` and not `[GMUFeature]`.
> 
> i.e.
> 
> ```
> for obj in geoJsonParser.features {
>   if let feature = obj as? GMUFeature {
>     let properties = feature.properties
>     // Do something with properties here
>   }
> }
> ```
Hi arriolac, I tried the above you provided. But it throws an error "Use of undeclared type 'GMUFeature' ". Could you suggest some other way to access properties?

**Comment by arriolac** [comment] 2020-03-05 16:52
@mallikarjuna0308 can you share a code snippet? The code I shared above runs just fine assuming the right import statements are in place.

**Comment by mallikarjuna0308** [comment] 2020-03-06 05:56
Thank you @arriolac for your response. I did not import anything, when I'm trying to import Google-Maps-iOS-Utils, it is throwing an error. Since I did not import any thing, I might be facing error while using your code. Could you please let me know what and where to import the library? If I still face the issue, I would share the code with you.
Note: I have used cocoapods to integrate Google-Maps-iOS-Utils library in my project.

**Comment by arriolac** [comment] 2020-03-06 17:11
You need to do the following at the top of your `.swift` files:
```swift
import GoogleMapsUtils
```

or at the top of your `.m` files for Obj-C:
```objective-c
@import GoogleMapsUtils;
```

You can refer to our samples directory to see how it's used: https://github.com/googlemaps/google-maps-ios-utils/tree/master/samples

**Comment by mallikarjuna0308** [comment] 2020-03-10 07:19
Hi @arriolac, sorry for the late reply. I tried to import GoogleMapsUtils as you mentioned above, but it's throwing an error " No such module 'GoogleMapsUtils' ". I have gone through the link you provided above too but still the error still persists. Could you please help me in this regard?

**Comment by mallikarjuna0308** [comment] 2020-03-11 07:38
Hi @arriolac, my problem got resolved. I used cocoapods to integrate this library and also added in library in Bridging-Header.h file as suggested in this link: https://developers.google.com/maps/documentation/ios-sdk/utility/kml-geojson
After commenting in header file, everything started working fine. Thanks a lot for your support @arriolac.

**Comment by arriolac** [comment] 2020-03-11 15:17
@mallikarjuna0308 glad you were able to get that working. Curious what version of this library are you using?

**Comment by mallikarjuna0308** [comment] 2020-03-12 05:12
@arriolac I'm using 'Google-Maps-iOS-Utils', '~> 3.0.2'

**Comment by Gustavopcaiafa** [comment] 2020-06-01 15:46
Hi there and sorry to reopen this, but i am facing something simmilar.

I'm trying to show the title of the area using GeoJson but somehow it just doesn't shows on the map. Im using iOS 11.0 and pod Google-Maps-iOS-Utils 3.1.4 & GoogleMaps 3.9.0

I just posted on StackOverflow with more details : [https://stackoverflow.com/questions/62135450/cannot-display-title-in-googlemaps-geojson-swift](url)

if someone can help i'll be very gratefull.  Thanks !

**Comment by chitgoks** [comment] 2022-11-09 11:40
> @juvs you should be able to access the properties of a feature, it requires some type checking though since `geoJsonParser.features` is of type `[GMUGeometryContainer]` and not `[GMUFeature]`.
> 
> i.e.
> 
> ```
> for obj in geoJsonParser.features {
>   if let feature = obj as? GMUFeature {
>     let properties = feature.properties
>     // Do something with properties here
>   }
> }
> ```

hi, i came across this thread because i do not know how to access feature.properties once it is rendered by GMUGeometryRenderer.render()

i thought at first that geoJsonParser.features link hand in hand with renderer.mapOverlays() but the overlays count too many compared to the features array of geoJsonParser.

i was looking at populating the userData property but there does not seem to be a way to do so?

There are other key values in the properties property that i need to access once rendered to screen. since there is no way to set click listeners for the GMUFeature unlike in android, how can this be possibly done through swiftui?
