### ISSUE TITLE
Please solve it quickly.

### ISSUE THREAD

**Issue by FizzXiaoyu** [googlemaps/google-maps-ios-utils#180] opened 2018-04-17 05:51 UTC
CoreData: annotation: Failed to load optimized model at path '/var/containers/Bundle/Application/5A7FB194-7AD8-49F2-BA55-461BEED745A1/征仔拍.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'

**Comment by domesticmouse** [comment] 2018-04-17 06:38
Duplicate of https://github.com/googlemaps/google-maps-ios-utils/issues/177 ?

**Comment by FizzXiaoyu** [comment] 2018-04-17 06:53
yes,But you didn't solve it.

**Comment by Ramani1994** [comment] 2018-05-22 06:03
please all member declare how to solve out this problem

**Comment by Ramani1994** [comment] 2018-05-22 06:03
same problem ni my project

"CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/B2FAE4F8-9037-4D83-9644-5153224258C9/VSMotionPanoramaViewExample.app/GoogleMaps.bundle/GMSCacheStorage.momd/Storage.omo' "

**Comment by navakanth** [comment] 2018-05-24 06:04
facing with same problem with sample application

**Comment by pisxid** [comment] 2018-05-25 08:15
Same problem:

CoreData: annotation:  Failed to load optimized model at path '/var/containers/Bundle/Application/0D400299-C537-4D0B-8D07-19F21E903DE9/MyAPP.app/GoogleMaps.bundle/GMSCacheStorage.momd/StorageWithTileProto.omo'

**Comment by slorber** [comment] 2018-07-04 10:55
same here, using react-native-maps on Expo SDK28 detached. The map appears blank with markers and polylines on it and I get this error on logs.

Anyone has a solution?

**Comment by domesticmouse** [comment] 2018-07-13 02:54
Quick question, is this set of errors to do with the Google Maps iOS Utility library, or the Google Maps for iOS SDK? Looking at the reported issue, I'm guessing the latter?

**Comment by domesticmouse** [comment] 2018-07-13 03:03
A couple of potentially useful links: 

- [issuetracker.google.com/64504919](https://issuetracker.google.com/issues/64504919)
- [stackoverflow.com/questions/47236769](https://stackoverflow.com/questions/47236769/failed-to-load-optimized-model-googlemaps-sdk-ios)

**Closed by domesticmouse** 2018-07-13 03:03 UTC
