### ISSUE TITLE
How to show Info window in iOS GoogleMaps on tapping on marker using clustering?

### ISSUE THREAD

**Issue by gduh** [googlemaps/google-maps-ios-utils#66] opened 2016-12-29 10:05 UTC
On my iOS project I use GoogleMaps framework and Google-Maps-iOS-Utils framework in order to use clustering markers on map.

Without using clustering, just Google Maps, when I create severals markers, setting title's property, a tap on it show an info window with the corresponding title.

But when I use clustering, a tap on a marker (cluster or an item, the result is the same) the info window does not appear although the properties title and snippet are filled, why ?

**Comment by mountainvat** [comment] 2016-12-29 23:27
Duplicate of https://github.com/googlemaps/google-maps-ios-utils/issues/63

**Closed by mountainvat** 2016-12-29 23:27 UTC
