### ISSUE TITLE
SPM is not available on Xcode 12.2 RC (Swift 5.3.1)

### ISSUE THREAD

**Issue by Scvairy** [googlemaps/google-maps-ios-utils#347] opened 2020-11-07 05:10 UTC
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version: macOS 11.0.1 Beta (20B5022a)
3. Library version and other environment information: Xcode 12.2 beta 4 (12B5044c)

#### Steps to reproduce

  1. Install Xcode 12.2 Release Candidate
  2. Build project with SPM-dependency on Google Maps Utils

#### Compile Error

```
Failed to build module 'GoogleMapsUtils' from its module interface; 
the compiler that produced it, 
'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)', 
may have used features that aren't supported by this compiler, 
'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'
```

**Comment by Scvairy** [comment] 2020-11-07 05:21
Same with Xcode 12.1.1 RC:
`Failed to build module 'GoogleMapsUtils' from its module interface;
the compiler that produced it, 
'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)', 
may have used features that aren't supported by this compiler, 
'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'`

**Comment by Scvairy** [comment] 2020-11-07 05:34
Looks like you should change `Build Libraries for Distribution` to “Yes” in the framework’s build settings

**Comment by arriolac** [comment] 2020-11-09 17:27
The `GoogleMapsUtils.xcframework` is already built with the flag `BUILD_LIBRARIES_FOR_DISTRIBUTION ` enabled and `SKIP_INSTALL` set to false which should built the frameworks with Module Stability enabled. That said, I'm, not sure your fix in #348 will address the issue you're seeing. See: https://github.com/googlemaps/google-maps-ios-utils/blob/main/.github/workflows/release.yml#L46...L50 I'll dig into this.

**Comment by arriolac** [comment] 2020-11-09 19:50
I was not able to reproduce this issue on Xcode 12.1

**Comment by Scvairy** [comment] 2020-11-10 13:28
I tried it on another mac and couldn't reproduce either. 
Must be something with my environment, sorry. 
And thank you. ☺️

**Comment by marckrenn** [comment] 2020-11-11 21:24
Unfortunately, we're experiencing this very issue on both 12.1. and 12.2

Apparently, the framework will only work on the _exact_ Swift version build as it was compiled on.

If you need additional infos, let me know @arriolac

**Comment by marckrenn** [comment] 2020-11-11 21:46
JFYI 3.3.0 seems to work. Haven't tested newer versions.

**Comment by arriolac** [comment] 2020-11-11 21:52
Interesting that 3.3.0 works. Nothing changed in how we generate the .xcframework between 3.3.0 and later versions. Will look into this again.

**Comment by arriolac** [comment] 2020-11-12 23:07
I'm still not able to reproduce this on Xcode 12.2 on an example project even while testing using a different Swift Language version (I tried Swift 5 and Swift 4.2 which both work). @marckrenn or @Scvairy, are either of you able to share an example project demonstrating this bug?

**Comment by anupamchugh** [comment] 2020-11-20 12:18
I'm facing the exact issue with another framework.

**Comment by RamblinWreck77** [comment] 2020-12-07 16:34
@anupamchugh Any resolution? Zendesk's iOS SDK is experiencing this exact issue when installing via SPM

https://github.com/zendesk/support_sdk_ios/

**Comment by libec** [comment] 2021-01-05 14:33
hey @arriolac I'm also facing this issue, created example Package that uses `GoogleMapsUtils` package, see https://github.com/libec/GoogleMapsUtilsPackageExample

I checked the script where XCFramework is created as you mentioned in https://github.com/googlemaps/google-maps-ios-utils/blob/main/.github/workflows/release.yml#L46...L50 

I'm not sure by this `BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`.

If you check build options in Xcode and turn actual setting names on (editor > Show Setting Names) you can see that key for `Build Libraries for Distribution` is `BUILD_LIBRARY_FOR_DISTRIBUTION`, not `BUILD_LIBRARIES_FOR_DISTRIBUTION` but that should not be the issue as the setting is set to YES in Xcode project as far as I can see.

If you would take a look at the example project and see if that works for you that'd be appreciated 👍 

btw. 3.3.0 does not work in my case, behaves the same as `.upToNextMinor(from: "3.4.2")`

**Comment by arriolac** [comment] 2021-06-03 16:19
Closing. Please let me know if anyone is still encountering this issue.

**Comment by EthanTheInnovator** [comment] 2021-06-03 21:41
What an odd coincidence. This issue hasn't been touched for months, but 5 hours after it was closed I am experiencing the same issue on Xcode 12.5.

Here is the error message: "Failed to build module 'GoogleMapsUtils' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'"

**Comment by EthanTheInnovator** [comment] 2021-06-03 21:52
I found [this similar issue](https://developer.apple.com/forums/thread/669440) which discusses using [Library Evolution in Swift](https://swift.org/blog/library-evolution/) to solve this issue. It enables the framework to be built in a way that future versions of the compiler are compatible with it.

**Comment by arriolac** [comment] 2021-06-03 22:01
PR #335 was supposed to enable library evolution support, but perhaps it is being overridden (or disabled) at some point during the build process. I'll look into this.

**Comment by EthanTheInnovator** [comment] 2021-06-04 18:41
In SPM, I set it to Up to Next Major Version, which means it should be the latest version of the library

**Comment by monRo** [comment] 2021-07-27 17:29
Any update on this? Having the same issue as @EthanTheInnovator has

**Comment by arriolac** [comment] 2021-07-27 17:47
I've had a lot of trouble to try to reproduce this last time I looked into this issue. To help with debugging / reproducing, @monRo can you share more details (i.e. your environment, stacktrace, etc.)?

**Comment by monRo** [comment] 2021-07-27 18:07
@arriolac sure I can.
Here we go:
Mac OS: 11.4
Xcode: 12.5.1
Steps to reproduce:
1. XCode -> New -> Project -> App -> Interface: Storyboard, Life Cycle: UIKit App Delegate, Language: Swift
2. Add new package dependency
3. Search by google maps utils
4. Add it to the project
5. Open ViewController.swift class
6. Add `import GoogleMapsUtils`
7. Build

At this point, I'm able to see the compiler error `Failed to build module 'GoogleMapsUtils' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'`

thx in advance

**Closed** 2021-07-29 22:57 UTC
Labels: triage me, type: bug

**Comment by arriolac** [comment] 2021-07-30 00:06
Please try with `v3.10.3`

**Comment by monRo** [comment] 2021-07-30 05:34
@arriolac what I'm doing wrong? Now can see another error:
`Failed to build module 'GoogleMapsUtils' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced`

**Comment by arriolac** [comment] 2021-07-30 06:03
Did you also include GoogleMaps as a dependency? Unfortunately GoogleMaps is not available in SPM yet so you'll need to do so with one of the install options (CocoaPods, Carthage or manually).

**Comment by monRo** [comment] 2021-07-30 06:26
@arriolac my bad, sorry, forgot to add it to a new fresh project. It works. Thanks

**Comment by nharbo** [comment] 2022-09-05 11:59
I'm having the same issue now:
```
Failed to build module 'GoogleMapsUtils'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.
```

Any suggestions on how to get on with this? Does it take a new version of the SDK? Currently installing with SPM and "4.1.0 - Next Major".
